services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - DOTENV_PATH=/app/.env
      - GIN_MODE=release
      - JWT_SECRET=${JWT_SECRET}
    restart: always
